<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="bi bi-search"></i>
					Siga o que lhe interessa.
				</div>
				<div class="communicationItem">
					<i class="bi bi-chat-dots"></i>
					Saiba sobre o que as pessoas estão falando.
				</div>
				<div class="communicationItem">
					<i class="bi bi-person-fill-add"></i>
					Participe da conversa.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 ps-5 pe-5">
		<form method="post" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" class="form-control" placeholder="E-mail" name="email">
				</div>
				<div class="col">
					<input type="text" class="form-control" placeholder="Senha" name="senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
		<?php if ($this->view->login == 'erro'): ?>
			<div class="text text-danger">Erro na autenticação de usuário</div>
		<?php endif; ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

				<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>